## variables
@base_url = http://127.0.0.1:8000/

### register user
POST {{base_url}}/api/auth/sign-up/
Content-Type: application/json

{
    "email": "gdvbhgbhb@gmail.com",
    "password": "Password123!",
    "username": "Dummy3"
}

### sign-in
POST {{base_url}}/api/auth/sign-in/
Content-Type: application/json

{
    "email": "gdvbhgbhb@gmail.com",
    "password": "Password123!"
}

### see account info

GET {{base_url}}/api/auth/u/

### updating info
PUT {{base_url}}/api/auth/u/update-info/
Content-Type: application/json

{
    "username": "Fahad Bin Ibrahim",
    "type": "customer",
    "status": "verified"
}

### getting new access token
GET {{base_url}}/api/auth/new-access-token/

### Setting new password
POST {{base_url}}/api/auth/u/change-password/
Content-Type: application/json

{
    "new_password": "123",
    "old_password": "I_love_django_34@"
}

### deleting user
DELETE {{base_url}}/api/auth/u/delete-account/