# Generated by Django 6.0.7 on 2026-08-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
