# Generated by Django 6.0.7 on 2026-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
